#!/bin/bash            # this line only there to enable syntax highlighting in this file
#NOGRAVITY                      # turn off self-gravity (compatible with analytic_gravity)
#FREEZE_HYDRO
#MAGNETIC
#BINISET
#TWODIMS
#NO_ISEND_IRECV_IN_DOMAIN
HYDRO_MESHLESS_FINITE_MASS
#BOX_PERIODIC
EOS_GAMMA=(5.0/3.0)
#COOLING
#COOL_LOW_TEMPERATURES
#COOL_MOLECFRAC=1
#RT_HYDROGEN_GAS_ONLY
#GR_COOLING
#EXACT_COOLING
#SECOND_ORDER_IMPLICIT
#TRUELOVE_CRITERION_PRESSURE
PMGRID=64
#PM_PLACEHIGHRESREGION=1+2+16+32
#PM_HIRES_REGION_CLIPPING=1000
GRAVITY_ACCURATE_FEWBODY_INTEGRATION
OPENMP=2
MULTIPLEDOMAINS=16
############# Adaptive
#ADAPTIVE_GRAVSOFT_FORGAS
ADAPTIVE_GRAVSOFT_FORALL=2
#ADAPTIVE_GRAVSOFT_FROM_TIDAL_CRITERION=2+32
##########
#GALSF
#GALSF_EFFECTIVE_EQS
#GALSF_SUBGRID_WINDS
#UNIFIED_WIND_STAR_GENERATION
#GALSF_SUBGRID_ENRICHMENT
#HOTWIND
#GALSF_SUBGRID_VARIABLEVELOCITY_DM_DISPERSION
#GALSF_WINDS_POLAR
#GALSF_SFR_MOLECULAR_CRITERION
#GALSF_SFR_VIRIAL_SF_CRITERION=0
SINGLE_STAR_SINK_DYNAMICS
SINGLE_STAR_TIMESTEPPING=2
HERMITE_INTEGRATION=2+32
#SINGLE_STAR_SINK_FORMATION=(0+1)
#SINGLE_STAR_SINK_FORMATION=(0+1+2+4+16)   # Switch to this one
#SINGLE_STAR_ACCRETION=7
#BH_BONDI=0
#SNIA_HEATING
#AGB_HEATING
BLACK_HOLES  # Turn this on
BH_SWALLOWGAS # Turn this on
BH_GRAVCAPTURE_NONGAS
#COLD_COOLING_ACCRETION
#BH_THERMALFEEDBACK
#EVALPOTENTIAL
#BH_REPOSITION_ON_POTMIN
#BH_DYNFRICTION=0
BH_DYNFRICTION_FROMTREE
#BH_DRAG=1
#HAVE_HDF5
USE_FFTW3
#NOTYPEPREFIX_FFTW
DOUBLEPRECISION_FFTW
#FOF
#FOF_PRIMARY_LINK_TYPES=2
#FOF_SECONDARY_LINK_TYPES=1+16+32
#FOF_GROUP_MIN_LEN=32
#OUTPUTACCELERATION
#INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
#INPUT_POSITIONS_IN_DOUBLE
#POPIIIBHSEED

DM_SIDM=2
### New flags for Igor's version
DM_SIDM_AREPO
SIDM_ISOTROPIC
PMAXLOW
DM_SIDM_VIS # For Yukawa scattering
#DM_SIDM_RES # For resonance scattering. Note new DM_g parameter
GRAVSOFTFACTOR
# Need empty blank line at end so final letter of config variable isn't cut off