#!/bin/bash            # this line only there to enable syntax highlighting in this file
#NOGRAVITY                      # turn off self-gravity (compatible with analytic_gravity)
#FREEZE_HYDRO
#MAGNETIC
#BINISET
#TWODIMS
#NO_ISEND_IRECV_IN_DOMAIN
HYDRO_MESHLESS_FINITE_MASS
#HYDRO_MESHLESS_FINITE_VOLUME
#BOX_PERIODIC
EOS_GAMMA=(5.0/3.0)

#SECOND_ORDER_IMPLICIT
#TRUELOVE_CRITERION_PRESSURE
PMGRID=64
#PM_PLACEHIGHRESREGION=1+2+16+32
#PM_HIRES_REGION_CLIPPING=1000

GRAVITY_ACCURATE_FEWBODY_INTEGRATION
#GRAVITY_HYBRID_OPENING_CRIT
#LONG_INTEGER_TIME
#TIDAL_TIMESTEP_CRITERION

OPENMP=2
MULTIPLEDOMAINS=16
############# Adaptive
#ADAPTIVE_GRAVSOFT_FORGAS
#ADAPTIVE_GRAVSOFT_FORALL=2
ADAPTIVE_GRAVSOFT_FROM_TIDAL_CRITERION=2+32

SINGLE_STAR_SINK_DYNAMICS
SINGLE_STAR_TIMESTEPPING=2
HERMITE_INTEGRATION=2+32 # DM + BH - I'm not sure it should be used for DM
#SINGLE_STAR_SINK_FORMATION=(0+1)
#SINGLE_STAR_SINK_FORMATION=(0+1+2+4+16)   # Switch to this one
#SINGLE_STAR_ACCRETION=7
#BH_BONDI=0

BLACK_HOLES  # Turn this on
BH_SWALLOWGAS # Turn this on
BH_GRAVCAPTURE_NONGAS
BH_OUTPUT_MOREINFO

#EVALPOTENTIAL
#BH_REPOSITION_ON_POTMIN
#BH_DYNFRICTION=0
BH_DYNFRICTION_FROMTREE
#BH_DRAG=1

#HAVE_HDF5
USE_FFTW3
#NOTYPEPREFIX_FFTW
DOUBLEPRECISION_FFTW
OUTPUT_TIMESTEP
#OUTPUT_ACCELERATION
#INPUT_IN_DOUBLEPRECISION
OUTPUT_IN_DOUBLEPRECISION
#INPUT_POSITIONS_IN_DOUBLE
#POPIIIBHSEED

#DM_SIDM=2
### New flags for Igor's version
## Needed regardless of what SIDM version is used:
PMAXLOW
# mutually exclusive
SIDM_ISOTROPIC
#SIDM_ANISOTROPIC
## SIDM versions:
#DM_SIDM_GIZMO
##DM_SIDM_AREPO
# AREPO SIDM flags
##DM_SIDM_VIS # For Yukawa scattering
##DM_SIDM_RES # For resonance scattering. Note new DM_g parameter
## Needed regardless of SIDM on/off:
GRAVSOFTFACTOR

DEVELOPER_MODE


# Need empty blank line at end so final letter of config variable isn't cut off
